# Connect-N Game

In [10]:
import numpy as np

In [399]:
class Board:    
    def __init__(self, N):
        '''Board for a Connect-N game, the board will have N+2 Col and N+3 Rows'''
        self.N = N
        self.num_row = N + 3
        self.num_col = N + 2        
        self.cols = [Column(self.num_row) for i in range(self.num_col)] # create N+2 columns
        self.player = 1
        self.icon = ['\u25CB','\u25CF','\u25B2']
        self.winner = 0
        self.players = ['玩家', '电脑']
        
    def status(self):
        bd = [x.getdata() for x in self.cols]
        bd = np.array(bd)[:,::-1].T
        return bd
    
    def display(self):
        '''display the board'''
        #print ('\u26AA' '\u26AB') # use these unicode to print your disk
        bd = self.status()
        #print(bd)
        #'\n%s\n' % ('-'*self.num_col) #[''.join([str(x) for x in line])
        txt = ('\n').join([''.join(map(str, line))  for line in bd.tolist()])
        #print(txt)
        txt = txt.replace('0',self.icon[0]).replace('1',self.icon[1]).replace('2',self.icon[2])
        print()
        print('重力棋游戏'.center(30,'-'))
        self.showtip()
        print(' '.join(map(str, range(1,7))))
        print(txt)
        print(' '.join(map(str, range(1,7))))
        print()
        self.showplayer()
        #return txt
        
    def drop_disk(self, c):
        '''drop a disk at column c'''
        pass
        if c <1 or c >self.num_col :
            print('你下错了，请输入范围:1-%d' % self.num_col)
            return False
        ret = self.cols[c-1].drop_disk(self.player)
        # 自动判断获胜情况
        if self.check_winning_condition():
            self.winner = self.player
        else:
            # 自动切换玩家
            self.changeplayer()
        return ret

    def check_winning_condition(self):
        '''check if there is a winner'''
        ret = False
        # 每个点沿右，右下，下，左下4个方向最多走3步，每一步都必须与当前点同色，如果能走到3步则表示获胜
        dire = [[0,1],[1,1],[1,0],[1,-1]]
        bd = self.status()
        for x in range(bd.shape[0]):
            for y in range(bd.shape[1]):
                po = bd[x,y]
                if po>0:
                    for d in dire:
                        step=0
                        xn,yn = x,y
                        for s in range(3):
                            # 计算下一个点的位置
                            xn,yn = xn+d[0],yn+d[1]
                            # 判断点是否在区域内
                            if 0<=xn<=self.num_row-1 and 0<=yn<=self.num_col-1:
                                if bd[xn,yn]==po:
                                    step += 1
                                else:
                                    break
                            else:
                                break
                        # 判断走了多少步
                        if step==3:
                            return True
        return ret
    
    def changeplayer(self):
        self.player = self.player-1 if self.player == 2 else 2

    def showtip(self):
        print('玩家：%s     电脑:%s\n' % tuple(self.icon[1:]))
    
    def showplayer(self):
        #print('当前轮到: [%s]玩家%d ' % (self.playericon(), self.player) )
        print('当前轮到: [%s]%s ' % (self.playericon(), self.players[self.player-1]) )
    
    def playericon(self):
        return self.icon[self.player]
        
class Column:
    def __init__(self, r):
        '''each column has r rows'''
        self.rows = [0]*r
    
    def drop_disk(self,player):
        if 0 in set(self.rows):
            index = self.rows.index(0)
            self.rows[index] = player
            return True
        else:
            print('下错了，该列已经放不下棋子')
            return False
    
    def getdata(self):
        return self.rows




## 测试棋盘显示

### 初始状态

In [37]:
N = 4 #standard Connect-4
board = Board(N)
board.display()


------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
1 2 3 4 5 6

当前轮到: [●]玩家1 


### 下棋对弃

In [38]:
N = 4 #standard Connect-4
board = Board(N)
board.drop_disk(3)
board.drop_disk(4)
board.display()

print(board.status())


------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○●▲○○
1 2 3 4 5 6

当前轮到: [●]玩家1 
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 2 0 0]]


## 测试下棋与切换玩家

In [23]:
board = Board(4)
board.drop_disk(4)
board.drop_disk(3)
board.display()



------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○▲●○○
1 2 3 4 5 6

当前轮到: [●]玩家1 


### 下错列

In [24]:
board = Board(4)
board.display()
board.drop_disk(0)



------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
1 2 3 4 5 6

当前轮到: [●]玩家1 
你下错了，请输入范围:1-6


False

### 某列已经下满

In [25]:
board = Board(4)
board.drop_disk(1)
board.drop_disk(1)

board.drop_disk(1)
board.drop_disk(1)

board.drop_disk(1)
board.drop_disk(1)

board.drop_disk(1)
board.display()
board.drop_disk(1)




------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
●○○○○○
▲○○○○○
●○○○○○
▲○○○○○
●○○○○○
▲○○○○○
●○○○○○
1 2 3 4 5 6

当前轮到: [▲]玩家2 
下错了，该列已经放不下棋子


False

## 测试获胜判断

In [26]:
board = Board(4)

board.drop_disk(4)
board.drop_disk(3)
board.display()

print('获胜状态：',board.check_winning_condition())



------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○▲●○○
1 2 3 4 5 6

当前轮到: [●]玩家1 
获胜状态： False


### 竖线判断

In [27]:
board = Board(4)
board.drop_disk(4)
board.drop_disk(3)
board.drop_disk(4)
board.drop_disk(3)
board.drop_disk(4)
board.drop_disk(3)
board.drop_disk(4)

board.display()

print('获胜状态：',board.check_winning_condition())



------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○●○○
○○▲●○○
○○▲●○○
○○▲●○○
1 2 3 4 5 6

当前轮到: [▲]玩家2 
获胜状态： True


### 横线判断

In [28]:
board = Board(4)

board.drop_disk(1)
board.drop_disk(2)

board.drop_disk(2)
board.drop_disk(3)

board.drop_disk(3)
board.drop_disk(4)

board.drop_disk(4)
board.drop_disk(5)

board.display()

print('获胜状态：',board.check_winning_condition())




------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○●●●○○
●▲▲▲▲○
1 2 3 4 5 6

当前轮到: [●]玩家1 
获胜状态： True


### 斜线判断

In [29]:
board = Board(4)

board.drop_disk(1)
board.drop_disk(2)

board.drop_disk(2)
board.drop_disk(3)

board.drop_disk(2)
board.drop_disk(3)

board.drop_disk(3)
board.drop_disk(4)

board.drop_disk(4)
board.drop_disk(4)

board.drop_disk(4)


board.display()

print('获胜状态：',board.check_winning_condition())


------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○●○○
○●●▲○○
○●▲●○○
●▲▲▲○○
1 2 3 4 5 6

当前轮到: [▲]玩家2 
获胜状态： True


In [30]:
board = Board(4)

board.drop_disk(6)
board.drop_disk(5)

board.drop_disk(5)
board.drop_disk(4)

board.drop_disk(5)
board.drop_disk(4)

board.drop_disk(4)
board.drop_disk(3)

board.drop_disk(3)
board.drop_disk(3)

board.drop_disk(3)


board.display()

print('获胜状态：',board.check_winning_condition())


------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○●○○○
○○▲●●○
○○●▲●○
○○▲▲▲●
1 2 3 4 5 6

当前轮到: [▲]玩家2 
获胜状态： True


## 游戏交互

In [31]:
print()
N=4
board = Board(N)
max_step = (N+2)*(N+3)
win = False
step = 0
player = board.player
while not win and step<max_step:
    board.display()
    win = board.check_winning_condition()
    if win: 
        print('\n胜利！ 获胜者：%s玩家%d' % (board.icon[player], player) )
        break
    while 1:
        c = input('请输入位置(1-%d):' % (N+2)).strip()
        c = int(c)
        player = board.player
        ret = board.drop_disk(c)
        if ret:
            step += 1
            break




------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
1 2 3 4 5 6

当前轮到: [●]玩家1 
请输入位置(1-6):3

------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○●○○○
1 2 3 4 5 6

当前轮到: [▲]玩家2 
请输入位置(1-6):4

------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○●▲○○
1 2 3 4 5 6

当前轮到: [●]玩家1 
请输入位置(1-6):3

------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○●○○○
○○●▲○○
1 2 3 4 5 6

当前轮到: [▲]玩家2 
请输入位置(1-6):4

------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○●▲○○
○○●▲○○
1 2 3 4 5 6

当前轮到: [●]玩家1 
请输入位置(1-6):4

------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○●○○
○○●▲○○
○○●▲○○
1 2 3 4 5 6

当前轮到: [▲]玩家2 
请输入位置(1-6):3

------------重力棋游戏-------------
玩家1：●     玩家2:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○▲●○○
○○●

## AI模拟

###  棋盘状态特征

棋盘状态特征的目的是针对当前棋盘状态，提取出棋子的特征值。

棋子的特征值可以分为针对游戏者双方分别给出特征值，提取的方法是相同的。

最终的特征为已方棋子特征加上对方棋子的特征,即：

`[[已方特征],[对方特征]]`


### 棋子特征


棋子特征主要是要能够描述棋子的好坏，棋子的发展变化情况，棋子离目标状态的远近。

这里参考围棋的思路，主要引入几个核心要素：棋串，棋长，真气，长气，气度等。



#### 棋串

棋串是指一个或者多个在一条直线上的棋子连成的串; 

棋串包括横向，竖向和斜向（正反）四个方向。

每个棋子可以包含在不同的棋串中。

棋串用chess表示

```
○○○○○○
○○▲○○○
○●●▲○○
```

上图中●方共有子串三个：
```
●     位置：((3,2))
●     位置：((3,3))
●●    位置：((3,2),(3,3))
```
▲方共有子串三个:

```
▲     位置：((3,2))
▲     位置：((3,3))
▲▲    位置：((2,3),(3,4)) 斜线
```



#### 棋长

棋长是指棋串的最大长度,是一个整数；

棋长用maxlen表示；

可以很容易推断出，对于N子棋来说：

* 当出现棋长为N的棋串表示已经胜利；
* 当前局面中最大的棋长为N-1


#### 真气

真气是指棋串周边可以下棋的空位位置，位置包括斜方向，与围棋的气的计算相同。

真气的数量越多，表示棋串未来的发展变化程度越大。

棋串的真气数量用gas_count表示；

对于真气为0的棋串，已经没有发展的空间，可以不需要参与计算；


#### 气度

棋串的每一个真气，有些真气是马上可以“落下棋”的位置，而有些是未来才能“落下棋”的位置；

气度就是要多少步才能“落下棋”到该位置，用一个整数来表示，0表示马上就可以落棋；

对于N子棋来说，气度的取值范围为0至N-1；

显然，气度为0的真气就是下一步要落子的位置。




####  长气

长气是指棋串的真气中，可以让棋长变大的真气；

长气的个数最小值为0，最大值为2；


#### 必胜局面
显然可见，对于4子棋来说，如果出现：一个棋串长度为3，长气个数为2，长气的气度均为0，则为必胜棋。
如下图：

```
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○▲▲▲○
○○●●●○
```

对于●方：

最大棋串的长度为3，真气个数为4，左右两边分别有一个长气，即长气个数为2，并且这两个长气的气度均为0。

此时无论对方下哪个位置，这两个位置二者必得其一，所以是必胜的局面。



#### 必应局面

对于4子棋来说，如果最大棋串长度为3，长气个数为1，且长气的气度为0，则为必应局面，也就是必须抢占这个位置。

如下图：

```
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○▲▲▲
○○○●●●
```

对于`●`方：

最大棋串长度为3，长气个数为1，气度为0，也就是再下到这里就获胜了，所以是双方抢占的位置。

对于已方来说，叫获胜位；对于对方来说，叫必应位。


### 棋盘状态表示

棋盘状态使用各个棋串表示，搜索出当前棋盘下的所有棋串，去除掉包含的子串以及死串。

使用棋串长度l，长气气度d1，长气气度d2 这三个值组成的特征数组表示一个棋串。
例如：
```
[3,1,1]  必胜棋串
[3,0,1]  必应棋串
[3,2,2]  带禁入的棋串， 
[2,0,2]  斜向有发展前途的棋串
```


使用以下公式来计算一个棋串的分值：
```
value = 10**(l+2) + 10**(l+1)/d1**3 + 10**(l+1)/d2**3 + 10**(l+1)/(d1*d2)**2 + 10**(l)/(d1+d2)**2
```

公式中，要排除掉d1,d2为0的情况，避免出现计算错误。

棋盘的总得分即为所有棋串的分值总和。

这样设计公式的原因是把棋串长度，气度1，气度2分别放在不同的位上进行区分；

当棋串长度从3变为4时，棋串得分立即从10万等级上长到100万等级，因此很容易判断是否获胜。

同时考虑了气度1、气度2为0；以及同时为1的情况，公式的设计可以实现同长度棋串的不同气度排序：
```
[x,1,1] > [x, 1, 2] > [x, 1, 3] > [x, 0,1] > [x, 0, 2]
```


### 棋串得分公式及验证

In [426]:
# 棋串得分计算公式
def chessvalue(l,d1,d2):
    
    if l<4 and  d1==d2==0: return 0
    value = 10**(l+2) 
    k1 = d1*d2
    k2 = d1+d2
    
    v1 = 0 if d1==0 else 10**(l+1)/d1**3
    v2 = 0 if d2==0 else 10**(l+1)/d2**3
    value += v1+v2
    if k1>0:
        value += (10**(l+1) / k1**1.5)
    if k2>0:
        value += (10**(l) / k2)
    #value *= 100
    return int(value)

testv = [[5,0,0],
         [4,1,1],
         [4,0,0],
         [4,0,1],
         [4,0,2],
    
         [3,1,1],
         [3,1,2],
         [3,1,3],
         [3,1,4],
         [3,0,1],
         [3,1,0],
         [3,2,2],
         [3,2,3],
         [3,2,4],    
         [3,0,2],
         [3,0,3],
         [3,0,0],
         
         [2,1,1],
         [2,0,1],
         [2,1,0],
         [2,1,2],
         [2,1,3],
         [2,0,2],
         [2,0,3],
         [2,1,4],
         [2,0,0],
         
         [1,1,1],
         [1,0,1],
         [1,0,0],
        ]

for x in testv:
    print('{0} ==> {1:>10,d}'.format(str(x), chessvalue(*x)))


[5, 0, 0] ==> 10,000,000
[4, 1, 1] ==>  1,305,000
[4, 0, 0] ==>  1,000,000
[4, 0, 1] ==>  1,110,000
[4, 0, 2] ==>  1,017,500
[3, 1, 1] ==>    130,500
[3, 1, 2] ==>    114,083
[3, 1, 3] ==>    111,731
[3, 1, 4] ==>    110,981
[3, 0, 1] ==>    111,000
[3, 1, 0] ==>    111,000
[3, 2, 2] ==>    103,375
[3, 2, 3] ==>    102,098
[3, 2, 4] ==>    101,729
[3, 0, 2] ==>    101,750
[3, 0, 3] ==>    100,703
[3, 0, 0] ==>          0
[2, 1, 1] ==>     13,050
[2, 0, 1] ==>     11,100
[2, 1, 0] ==>     11,100
[2, 1, 2] ==>     11,408
[2, 1, 3] ==>     11,173
[2, 0, 2] ==>     10,175
[2, 0, 3] ==>     10,070
[2, 1, 4] ==>     11,098
[2, 0, 0] ==>          0
[1, 1, 1] ==>      1,305
[1, 0, 1] ==>      1,110
[1, 0, 0] ==>          0


### 人工智能类

In [427]:

# 人工智能类
    
class AI:
    
    def __init__(self,bd):
        # 复制状态，注意是已经旋转过的
        self.board = bd.status().copy()
        pass
    
    def score(self):
        allchess = self.all_chess()
        v = list(map(lambda y: sum(map(lambda x:x[-1], y)), allchess))
        return v
        
    def nextstep(self, player):
        '''预测出下一步最好的棋应该下在哪里'''
        
        '''计算下一步可下棋的位置'''
        pos = np.where (self.board[0]==0)[0]+1
        #print(pos)
        
        #模拟在某一列下一个棋
        def dropstep(bd,col,player):
            bd = bd.copy()
            #print('-'*30)
            #print(bd)
            k = bd[:, col][::-1]
            row = bd.shape[0] - k.tolist().index(0) - 1
            bd[row,col] = player
            #print('-'*30)
            #print('drop:',col)
            #print(bd)
            return bd
        
        # 当前得分
        current_score = np.array(self.score())
        #print('current_score:', current_score)
        
        #分别计算每一个可下位置下棋后的状态得分变化值
        def nextscore(bd, current_score, player):
            nplayer = 1 if player==2 else 2
            f_score = np.array([current_score] * bd.shape[1])
            '''计算下一步可下棋的位置'''
            pos = np.where (self.board[0]==0)[0]
            for p in pos:
                #模拟下一步棋后的状态
                nbd = dropstep(bd, p, player)
                # 计算状态及得分
                v_chess = self.all_chess(board=nbd)
                v_score = list(map(lambda y: sum(map(lambda x:x[-1], y)), v_chess))
                f_score[p] = v_score
            f_score -= current_score
            return f_score
     
        score_change = nextscore(self.board, current_score, player )
        #print('score_change:', score_change)
        pp = [1,-2]
        if player == 2:
            pp = [-2, 1] 
        score_change = score_change * pp

        # 得分变化计算方式：已方增加值值 - 对方增加值
        t_score = score_change[:,0] - score_change[:,1]
        #print(t_score)
        # 排序
        idx = np.array(t_score).argsort()[::-1] + 1
        #print('sorted:', idx)
        nt = np.sort(t_score,axis=0)[::-1]
        
        #ns = np.sort(score_change,axis=0)[::-1]
        #nf =  np.sort(f_score,axis=0)[::-1]
        
        rpos = list(zip(idx, nt.tolist())) #, ns.tolist(), nm.tolist()
        return rpos


    
    def all_chess(self, board=None):
        '''盘面分析，获取所有的棋串，并计算得分'''
        
        #判断子串重复
        check_repeat = lambda m,n: all( map(lambda x:x in n, m))
        
        ret = [[],[]]
        # 每个点沿右，右下，下，左下4个方向最多走3步，每一步都必须与当前点同色，如果能走到3步则表示获胜
        dire = [[0,1],[1,1],[1,0],[1,-1]]
        if board is None:
            bd = self.board
        else:
            bd = board
        for x in range(bd.shape[0]):
            for y in range(bd.shape[1]):
                po = bd[x,y]
                if po>0:
                    #ret[po-1].append([(x,y)])
                    for d in dire:
                        step=0
                        chess = []
                        #chess.append(po)
                        chess.append((x,y))
                        xn,yn = x,y
                        #----- 计算气度1:d1
                        d1 = 0
                        px, py = x-d[0],y-d[1]
                        if 0<=px<bd.shape[0] and 0<=py<bd.shape[1]:
                            if bd[px,py]==0:
                                k = bd[:, py][::-1][:bd.shape[0]-px]
                                d1 = len(list(filter(lambda x:x==0,k)))
                        #-----
                        #最大深入3级
                        for s in range(3):
                            # 计算下一个点的位置
                            xn,yn = xn+d[0],yn+d[1]
                            # 判断点是否在区域内
                            if 0<=xn<bd.shape[0] and 0<=yn<bd.shape[1]:
                                if bd[xn,yn]==po:
                                    chess.append((xn,yn))
                                    step += 1
                                else:
                                    break
                            else:
                                break
                        #----- 计算气度2：d2
                        d2 = 0
                        #xn,yn = xn+d[0],yn+d[1]
                        if 0<=xn<bd.shape[0] and 0<=yn<bd.shape[1]:
                                if bd[xn,yn]==0:
                                    k = bd[:, yn][::-1][:bd.shape[0]-xn]
                                    d2 = len(list(filter(lambda x:x==0,k)))
                        #-----
                        # 记录棋串
                        #if step>0:
                        # 判断是重重复
                        if not any(map(lambda x:check_repeat(chess,x[0]), ret[po-1])):
                            value = chessvalue(len(chess),d1,d2)
                            ret[po-1].append([chess,[len(chess), d1, d2],value])
                        # 记录棋串长度，气度1，气度2
        # 棋串排序,按棋长
        #mysort = lambda r: sorted(r,key=lambda x:-len(x[0]))
        # 棋串排序,按棋串得分
        mysort = lambda r: sorted(r,key=lambda x:-x[-1])
        ret = list(map(mysort,ret))
        return ret
    
class Chess:
    def __init__(self,dat):
        self.dat = dat
        pass
    def __str__(self):
        return map(str,self.dat)
    

####  模拟一个局面来进行评估

In [428]:
board = Board(4)

board.drop_disk(6)
board.drop_disk(5)

board.drop_disk(5)
board.drop_disk(4)

board.drop_disk(5)
board.drop_disk(4)

board.drop_disk(4)
board.drop_disk(3)

board.drop_disk(3)
board.drop_disk(3)

#board.drop_disk(3)

board.display()

ai = AI(board)
allchess = ai.all_chess()
#v = map(lambda y: sum(map(lambda x:x[-1], y)), allchess)
v1, v2 = ai.score()

print('棋盘状态:')
print('玩家1  得分:{0:,d}'.format(v1))
ret = list(map(print,allchess[0]))
print('-'*30)

print('玩家2  得分:{0:,d}'.format(v2))
ret = list(map(print,allchess[1]))




------------重力棋游戏-------------
玩家：●     电脑:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○▲●●○
○○●▲●○
○○▲▲▲●
1 2 3 4 5 6

当前轮到: [●]玩家 
棋盘状态:
玩家1  得分:145,325
[[(4, 3), (5, 4), (6, 5)], [3, 1, 0], 111000]
[[(4, 3), (5, 2)], [2, 1, 1], 13050]
[[(4, 4), (5, 4)], [2, 1, 0], 11100]
[[(4, 3), (4, 4)], [2, 0, 2], 10175]
------------------------------
玩家2  得分:212,413
[[(6, 2), (6, 3), (6, 4)], [3, 1, 0], 111000]
[[(4, 2), (5, 3), (6, 4)], [3, 4, 0], 100406]
[[(4, 2)], [1, 3, 0], 1007]
[[(5, 3), (6, 3)], [2, 0, 0], 0]
[[(5, 3), (6, 2)], [2, 0, 0], 0]


#### 输出推荐结果，第几列，分值变化量

In [429]:
recommand = ai.nextstep(1)
print(recommand)
print('-'*30)
recommand = ai.nextstep(2)
print(recommand)

[(3, 892909), (5, 198948), (4, 23813), (6, 23125), (1, 1110), (2, -123436)]
------------------------------
[(3, 210798), (5, 24983), (1, -1110), (6, -1850), (4, -10635), (2, -995407)]


### 使用AI模拟推荐对弃

In [408]:
print()
N=4
board = Board(N)
max_step = (N+2)*(N+3)
win = False
step = 0
# 记录步骤
allstep, nstep = [], []
while not win and step<max_step:
    board.display()
    if board.winner: 
        allstep.append(nstep)
        print('\n胜利！ 获胜者：%s%s' % (board.icon[board.winner], board.players[board.winner-1]) )
        break    
    # ----- 加入AI -----
    ai = AI(board)
    v1, v2 = ai.score()
    print('玩家得分:{0:,d}  电脑得分:{1:,d}'.format(v1,v2))
    recommand = ai.nextstep(board.player)
    print('AI推荐走法：',recommand )
    if board.player ==2:
        print("电脑走棋：%d" % recommand[0][0])
        board.drop_disk(recommand[0][0])
        # 记录
        nstep.append(recommand[0][0])
        allstep.append(nstep)
        nstep = []
        
        board.display()
    print()
    # ----- AI结束 -----
    #win = board.check_winning_condition()
    if board.winner: 
        print('\n胜利！ 获胜者：%s%s' % (board.icon[board.winner], board.players[board.winner-1]) )
        break
    while 1:
        c = input('请输入位置(1-%d):' % (N+2)).strip()
        c = int(c)
        ret = board.drop_disk(c)
        if ret:
            nstep.append(c)
            step += 1
            break
            
print('对弈过程:%s' % str(allstep))            



------------重力棋游戏-------------
玩家：●     电脑:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
1 2 3 4 5 6

当前轮到: [●]玩家 
玩家得分:0  电脑得分:0
AI推荐走法： [(5, 1105), (4, 1105), (3, 1105), (2, 1105), (6, 1010), (1, 1010)]

请输入位置(1-6):1

------------重力棋游戏-------------
玩家：●     电脑:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
●○○○○○
1 2 3 4 5 6

当前轮到: [▲]电脑 
玩家得分:1,010  电脑得分:0
AI推荐走法： [(2, 2020), (5, 1105), (4, 1105), (3, 1105), (6, 1010), (1, 1005)]
电脑走棋：2

------------重力棋游戏-------------
玩家：●     电脑:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
●▲○○○○
1 2 3 4 5 6

当前轮到: [●]玩家 

请输入位置(1-6):1

------------重力棋游戏-------------
玩家：●     电脑:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
●○○○○○
●▲○○○○
1 2 3 4 5 6

当前轮到: [▲]电脑 
玩家得分:11,110  电脑得分:1,010
AI推荐走法： [(2, 11105), (1, 11105), (3, 9090), (5, 1105), (4, 1105), (6, 1010)]
电脑走棋：2

------------重力棋游戏-------------
玩家：●     电脑:▲

1 2 3 4 5 6
○○○○○○
○○○○○○
○○○○○○
○○○○○○
○○○○○○
●▲○○○○
●▲○○○○
1 2 3 4 5 6

当前轮到: [●]玩家 

请